export { default as Logo } from "./image/Logo.svg";
export { default as HeaderMainBack } from "./image/headerMain.svg";
export { default as BittaHola } from "./image/Subtract.svg";
export { default as MainKonec } from "./image/Subtract12.svg";
export { default as Mishka } from "./image/mishka.svg";
export { default as Devkas } from "./image/kakayatodevka.svg";
export { default as Deva1 } from "./image/Group 63.svg";
export { default as Card11w } from "./image/card11.svg";
export { default as Card22 } from "./image/Card2.svg";
export { default as Devochka } from "./image/Mask group.svg";
export { default as Books } from "./image/low-angle-of-stacked-books-a-graduation-cap-and-ladders-for-education-day-PhotoRoom.svg";
export { default as Montserrat } from "./fonts/montserrat/Montserrat-Regular.ttf";
